spring:
  application:
    name: genie-backend
  config:
    encoding: UTF-8
server:
  port: 8080
logging:
  level:
    root: INFO
llm:
  default:
    base_url: '<input llm server here>'
    apikey: '<input llm key here>'
    interface_url: '/chat/completions'
    model: gpt-4.1
  settings: '{"claude-3-7-sonnet-v1": {
        "model": "claude-3-7-sonnet-v1",
        "max_tokens": 8192,
        "temperature": 0,
        "base_url": "<input llm server here>",
        "apikey": "<input llm key here>",
        "interface_url": "/chat/completions",
        "max_input_tokens": 128000
    }}'

autobots:
  autoagent:
    planner:
      system_prompt: planner.system_prompt.md
      next_step_prompt: planner.next_step_prompt.md
      max_steps: 40
      model_name: gpt-4.1
      pre_prompt: 一步一步（step by step）思考，结合用户上传的文件分析用户问题，并根据问题制定计划，用户问题如下：
      close_update: 1
    executor:
      system_prompt: executor.system_prompt.md
      next_step_prompt: executor.next_step_prompt.md
      sop_prompt: '{}'
      max_steps: 40
      model_name: gpt-4.1
      max_observe: 10000
    react:
      system_prompt: react.system_prompt.md
      next_step_prompt: react.next_step_prompt.md
      max_steps: 40
      model_name: claude-3-7-sonnet-v1
    tool:
      plan_tool:
        desc: tool.plan_tool.desc.md
        params: tool.plan_tool.params.json
      code_agent:
        desc: tool.code_agent.desc.md
        params: tool.code_agent.params.json
      report_tool:
        desc: tool.report_tool.desc.md
        params: tool.report_tool.params.json
      file_tool:
        desc: tool.file_tool.desc.md
        params: tool.file_tool.params.json
        truncate_len: 30000
      deep_search_tool:
        desc: 这是一个搜索工具，可以搜索各种互联网知识
        params: '{}'
      deep_search:
        params: tool.deep_search.params.json
        page_count: 5
        src_config: '{}'
        message:
          truncate_len: 20000
        file_desc:
          truncate_len: 1500
      task_complete_desc: 当前task完成，请将当前task标记为 completed
      clear_tool_message: 1
    task:
      pre_prompt: "先输出100字以内的文字内容确定下一步的行动（其中文字内容不要重复之前的思考内容，不能透露代码、链接等。严禁使用Markdown格式输出）。然后必须输出工具工具调用来完成当前任务。"
    tool_list: '{}'
    code_interpreter_url: "http://127.0.0.1:1601"
    deep_search_url: "http://127.0.0.1:1601"
    mcp_client_url: "http://127.0.0.1:8188"
    mcp_server_url: "https://mcp.api-inference.modelscope.net/1784ac5c6d0044/sse"
    summary:
      system_prompt: summary.system_prompt.md
      message_size_limit: 1500
    digital_employee_prompt: digital_employee_prompt.md
    struct_parse_tool_system_prompt: struct_parse_tool_system_prompt.md
    open_think_function_call_split: '{}'
    struct_pre_post_prompt_config: struct_pre_post_prompt_config.json
    sensitive_patterns: '{}'
    output_style_prompts: '{"html": "", "docs": "，最后以 markdown 展示最终结果", "table": "，最后以excel 展示最终结果", "ppt": "，最后以 ppt 展示最终结果"}'
    message_interval: '{}'
    user_name: ''
    default_model_name: gpt-4.1
    genie_sop_prompt: genie_sop_prompt.md
    genie_base_prompt: genie_base_prompt.md
