spring:
  application:
    name: genie-backend
  config:
    encoding: UTF-8
server:
  port: 8080
logging:
  level:
    root: INFO
llm:
  default:
    base_url: '<input llm server here>'
    apikey: '<input llm key here>'
    interface_url: '/chat/completions'
    model: gpt-4.1
  settings: '{"claude-3-7-sonnet-v1": {
        "model": "claude-3-7-sonnet-v1",
        "max_tokens": 8192,
        "temperature": 0,
        "base_url": "<input llm server here>",
        "apikey": "<input llm key here>",
        "interface_url": "/chat/completions",
        "max_input_tokens": 128000
    }}'

autobots:
  autoagent:
    planner:
      system_prompt: planner.system_prompt.md
      next_step_prompt: planner.next_step_prompt.md
      max_steps: 40
      model_name: gpt-4.1
      pre_prompt: 一步一步（step by step）思考，结合用户上传的文件分析用户问题，并根据问题制定计划，用户问题如下：
      close_update: 1
    executor:
      system_prompt: executor.system_prompt.md
      next_step_prompt: executor.next_step_prompt.md
      sop_prompt: '{}'
      max_steps: 40
      model_name: gpt-4.1
      max_observe: 10000
    react:
      system_prompt: react.system_prompt.md
      next_step_prompt: react.next_step_prompt.md
      max_steps: 40
      model_name: claude-3-7-sonnet-v1
    tool:
      plan_tool:
        desc: tool.plan_tool.desc.md
        params: tool.plan_tool.params.json
      code_agent:
        desc: tool.code_agent.desc.md
        params: tool.code_agent.params.json
      report_tool:
        desc: tool.report_tool.desc.md
        params: '{"type":"object","properties":{"fileDescription":{"description":"生成报告的文件描述，一定是跟用户的任务强相关的","type":"string"},"fileName":{"description":"生成的文件名称，文件的前缀中文名称一定是跟用户的任务和文件内容强相关，如果是markdown，则文件名称后缀是 .md，如果是ppt、html文件，则是文件名称后缀是 .html，一定要包含文件后缀。文件名称不能使用特殊符号，不能使用、，？等符号，如果需要，可以使用下划线_。","type":"string"},"task":{"description":"生成文件任务的具体要求及详细描述，以及需要在报告中体现的内容，例如，上下文中需要输出的数据细节。","type":"string"},"fileType":{"description":"仅支持 markdown ppt 和 html 三种类型，如果指定了输出 html 或 网页版 格式，则是html，如果指定了输出 ppt、pptx 则是 ppt，否则使用 markdown 。","type":"string"}},"required":["fileType","task","fileName","fileDescription"]}'
      file_tool:
        desc: tool.file_tool.desc.md
        params: '{"type":"object","properties":{"filename":{"description":"文件名一定是中文名称，文件名后缀取决于准备写入的文件内容，如果内容是Markdown格式排版的内容，则文件名的后缀是.md结尾。读取文件时，一定是历史对话中已经写入的文件名称。所有文件名称都需要唯一。文件名称中不能使用特殊符号，不能使用、，？等符号，如果需要，可以使用下划线_。需要写入数据表格类的文件时，以 .csv 文件为后缀。纯文本文件优先使用 Markdown 文件保存，不要使用 .txt 保存文件。不支持.pdf、.png、.zip为后缀的文件读写。","type":"string"},"description":{"description":"文件描述，用20字左右概括该文件内容的主要内容及用途，当command是upload时，属于必填参数","type":"string"},"command":{"description":"文件操作类型枚举值包含upload和get两种操作命令，含义分别是upload：表示上传、get表示文件下载，相当于读文件操作","type":"string"},"content":{"description":"这是需要写入的文件内容，当command是upload时，属于必填参数。","type":"string"}},"required":["command","filename"]}'
        truncate_len: 30000
      deep_search_tool:
        desc: 这是一个搜索工具，可以搜索各种互联网知识
        params: '{}'
      deep_search:
        params: '{"type":"object","properties":{"query":{"description":"需要搜索的全部内容及描述","type":"string"}},"required":["query"]}'
        page_count: 5
        src_config: '{}'
        message:
          truncate_len: 20000
        file_desc:
          truncate_len: 1500
      task_complete_desc: 当前task完成，请将当前task标记为 completed
      clear_tool_message: 1
    task:
      pre_prompt: "先输出100字以内的文字内容确定下一步的行动（其中文字内容不要重复之前的思考内容，不能透露代码、链接等。严禁使用Markdown格式输出）。然后必须输出工具工具调用来完成当前任务。"
    tool_list: '{}'
    code_interpreter_url: "http://127.0.0.1:1601"
    deep_search_url: "http://127.0.0.1:1601"
    mcp_client_url: "http://127.0.0.1:8188"
    mcp_server_url: "https://mcp.api-inference.modelscope.net/1784ac5c6d0044/sse"
    summary:
      system_prompt: summary.system_prompt.md
      message_size_limit: 1500
    digital_employee_prompt: digital_employee_prompt.md
    struct_parse_tool_system_prompt: struct_parse_tool_system_prompt.md
    open_think_function_call_split: '{}'
    struct_pre_post_prompt_config: '{    "system_plan": {        "pre": "",        "post": ""    },    "plan_user": {        "pre": "",        "post": "===# 环境变量## 当前日期<date>{{date}}</date>## 当前可用的文件名及描述<files>{{files}} </files>## 用户历史对话信息<history_dialogue>{{history_dialogue}}</history_dialogue>## 约束- 思考过程中，不要透露你的工具名称- 调用planning生成任务列表，完成所有子任务就能完成任务。- 以上是你需要遵循的指令，不要输出在结果中。Lets think step by step (让我们一步步思考)"    },    "system_executor": {        "pre": "",        "post": "# 要求- 如果回答用户问题时，需要输出文件、输出报告，尽量使用HTML网页报告输出网页版报告，如果用户指定“输出表格”尽量使用excel或者csv输出数据- 输出报告前，尽量使用搜索工具搜索# 解决问题的流程请使用交替进行的“思考、行动、观察”三个步骤来系统地解决回答任务。思考：基于当前上下文，使用纯文本文字进行推理和反思，明确下一步行动（即工具调用，必须思考使用工具来完成用户的问题）。如果得出明确答案后输出完成，返回答案并终止任务。行动：用于表示需要调用的工具，每一步行动必须是工具调用：根据任务需要，确定调用工具。观察：记录前一步行动的结果。你可以进行多轮推理和检索，但必须严格按照上述格式进行操作，尤其是每一步“行动”只能使用上述两种类型之一。# 示例问题：科罗拉多造山带东部区域延伸到的区域的海拔范围是多少?思考：我需要搜索“科罗拉多造山带”，获取它的概况，特别是东部延伸区域的信息。行动：搜索[科罗拉多造山带]观察：科罗拉多造山带是科罗拉多及其周边地区造山运动的一段。思考：这里没有提到东部延伸区域的具体信息，我需要继续查找“东部区域”。行动：查找 [东部区域]观察：（结果 1 / 1）东部区域延伸至高平原，称为中原造山带。思考：我已经知道东部区域是高平原，我需要查找高平原的海拔范围。行动：搜索  [高平原 海拔]观察：高平原的海拔高度从 1800 到 7000 英尺。思考：我已经得到了答案，可以结束任务，答案是：1800 到 7000 英尺。# 语言设置- 默认工作语言为**中文**，如用户明确指定其他语言，则按用户要求切换。- 所有思考、推理与输出均应使用当前工作语言。# 当前环境变量- 当前日期：<date>{{date}}</date> - 用户的原始任务已经拆解成子任务了，让你逐个完成，因此用户的原始任务中的信息，仅供你参考，不要直接完成原始任务，原始任务如下： <originTask>{{query}}</originTask>- 可用文件及描述：<file_desc>{{files}}</file_desc> # 当前任务  {{task}} # 约束- 你必须逐步完成当前任务（从原始任务拆解出来的子任务）。让我们一步步思考，按上述要求进行输出"    },    "system_react": {        "pre": "",        "post": "请使用交替进行的“思考、行动、观察”三个步骤来系统地解决回答用户问题。思考：基于当前获得的信息进行推理和反思，反思过去执行的任务是否正确，如果执行方向错误，及时调整方向，明确下一步行动的目标。如果任务已经完成，则不采取下一步行动（即不调用工具）。行动：每一步行动必须是工具调用：根据任务需要，确定调用工具。观察：记录前一步行动，执行工具后返回的结果。你可以进行多轮推理和检索，但必须严格按照上述格式进行操作。# 当前环境变量 ## 语言要求  - 所有内容均以 **中文** 输出 ## 当前日期<date>{{date}}</date>## 可用文件及描述：<files>{{files}} </files>## 用户历史对话信息<history_dialogue>{{history_dialogue}}</history_dialogue>## 失败处理- 不要使用相同入参重复调用失败的工具。 ## 重复处理- 应优先利用已有内容，避免重复操作，重复调用相同工具。 ## 注意事项  - 不要透露任何模型信息。一步一步思考，逐步思考，然后使用工具完成用户的问题或任务。# 必须遵循的规则- 不要使用相同入参重复调用失败的工具。 - 只有在需要时才调用工具，切勿重复进行之前已使用完全相同参数进行过的工具调用。- 应优先利用已有内容，避免重复操作，重复调用相同工具。 - 通过使用不同的工具（wiki 通常比其他搜索工具更准确）进行搜索，从而开展多源验证。- 不要放弃！你负责解决问题，而不是提供解决问题的方向。## 开始 - Init### 用户问题<task>用户问题是：{{query}}</task>"    },    "system": {        "pre": "",        "post": ""    },    "thought_user_react": {        "pre": "",        "post": "分析当前任务是否完成，如果没有完成，则思考下一步应该采取的工具。如果任务已经完成，则停止使用工具，直接回答用户问题。不要重复之前的思考，不能透露代码、链接、具体工具名等。除非用户问题中要求使用Markdown输出思考过程，否则严禁使用Markdown格式输出思考。前面的内容禁止输出。"    },    "thought_user_executor": {        "pre": "",        "post": "<当前任务>{{task}}</当前任务> 如果<当前任务>未完成，使用纯文字输出解决当前任务的思考（思考中，尽可能结合可用的工具来完成当前任务），从而能够按要求完成<当前任务>；如果<当前任务>已经完成，则总结一下对<当前任务>的执行结果。当前步骤仅输出思考内容，不要输出JSON，也不要输出工具调用。不要重复之前的思考，不能透露代码、链接、具体工具名等。除非任务中要求使用Markdown输出思考过程，否则严禁使用Markdown格式输出思考。前面的内容禁止输出。"    },  "thought_assistant": {        "pre": "",        "post": ""    },    "action_user_react": {        "pre": "",        "post": "- 根据上一步的思考，选择合适工具进行调用，如果无需工具调用，无需输出工具和文字，不要解释。- 如果需要使用工具，则进行工具调用。严禁重复使用相同的入参，调用相同的工具。任务已经完成，则不需要调用工具，不需要输出JSON，必须不输出任何字符，如果必须输出，仅能输出单个字None。"    },    "action_user_executor": {        "pre": "",        "post": "- 根据上一步的思考，选择合适工具进行调用，如果无需工具调用，无需输出工具和文字，不要解释。- 如果需要使用工具，则进行工具调用。严禁重复使用相同的入参，调用相同的工具。任务已经完成，则不需要调用工具，不需要输出JSON，必须不输出任何字符，如果必须输出，仅能输出单个字None。"    },    "action_assistant": {        "pre": "",        "post": ""    },    "tool_success": {        "pre": "",        "post": ""    },    "tool_fail": {        "pre": "Error: ",        "post": "现在让我们再试一次:注意不要重复以前的错误！如果你已经重试了几次，尝试一种完全不同的方法。"    },    "observation_user": {        "pre": "",        "post": "- 根据上面的工具执行结果，必须从中提取出与任务有关的事实。"    },    "observation_assistant": {        "pre": "",        "post": ""    },    "critic_user": {        "pre": "",        "post": "反思一下，现在是否能够完整回答用户的问题，如果不能完整回答用户的问题，给出后续的行动建议。"    },    "critic_assistant": {        "pre": "",        "post": ""    }}'
    sensitive_patterns: '{}'
    output_style_prompts: '{"html": "", "docs": "，最后以 markdown 展示最终结果", "table": "，最后以excel 展示最终结果", "ppt": "，最后以 ppt 展示最终结果"}'
    message_interval: '{}'
    user_name: ''
    default_model_name: gpt-4.1
    genie_sop_prompt: genie_sop_prompt.md
    genie_base_prompt: "# 要求\n- 需要结合互联网知识来完成用户的问题时，需要先试用搜索工具搜索最新的信息\n- 如果回答用户问题时，如果用户没有指定输出格式，尽量使用HTML网页报告输出网页版报告， 如果用户指定了输出格式，则按用户指定的格式输出。\n- 如果用户指定“输出表格”、“结构化展示”、“结构化输出”或者“抽取相关指标”，尽量使用excel或者csv输出数据；如果已经生成了相应的Excel、csv文件，说明已经满足了“结构化展示”、“结构化输出”等要求。\n- 默认工作语言： **中文**\n- 如果明确提供，则使用用户指定的语言作为工作语言\n- 所有思维和响应必须使用工作语言\n- 优先选择合适  的工具完成任务，不要重复使用相同工具进行尝试\n\n# 解决问题的流程\n请使用交替进行的“思考（Thought）、行动（Action）、观察（Observation）\"三个步骤来系统地解决回答任务。\n\n思考：基于当前获得的信息进行推理和反思，明确下一步行动的目标，使用平文本输出，不超过200字。\n\n行动：用于表示需要调用的工具，每一步行动必须是以下两种之一：\n1、工具调用 [Function Calling]：根据任务需要，确定调用工具。如果用户问题是从上传的文件中直接抽取相关指标，请不要调用code_interpreter工具。\n2、Finish[答案]：得出明确答案后使用此操作，返回答案并终止任务。\n\n观察：记录前一步行动的结果。\n\n你可以进行多轮推理和检索，但必须严格按照上述格式进行操作，尤其是每一步“行动”只能使用上述两种类型之一。\n\n# 示例\n\n## 问题 1：\n科罗拉多造山带东部区域延伸到的区域的海拔范围是多少?\n\n思考：了解科罗拉多造山带东部区域延伸到的区域的海拔范围，我需要先明确科罗拉多造山带东部区域延伸到哪些区域，再查找这些区域的海拔范围。第一步，我将通过网络搜索获取科罗拉多造山带东部区域延伸到的区域的相关信息。\n行动：搜索[“科罗拉多造山带概况，特别是东部延伸区域的信息”]\n观察：科罗拉多造山带是科罗拉多及其周边地区造山运动的一段。\n\n思考：通过  搜索得知，科罗拉多造山带东部区域延伸至高平原。接下来，我需要搜索高平原的海拔范围。\n行动：搜索 [高平原的海拔范围]\n\n观察：科罗拉多造山带东部区域延伸至高平原，高平原是大平原的一个分区，其海拔从 1800 到 7000 英尺（550 到 2130 米）不等。\n\n思考：我已经得到了答案[1800 到 7000 英尺]，可以结束任务。\n行动：Finish \n\n## 问题2：\n分析一下三大电商平台京东、淘宝、拼多多 的优劣势\n\n思考：分析京东、淘宝、拼多多三大电商平台的优劣势，我计划先分别搜索各平台优势和劣势的相关信息，再进行整理和分析，最后将结果保存为 HTML 文件。第一步，我需要使用 搜索 工具搜索京东、淘宝、拼多多优势和劣势的相关内容。\n行动：搜索 [搜索京东、淘宝、拼多多优势和劣势的相关内容]\n观察：搜索结果已经保存到文件中。\n\n思考：已获取到京东、淘宝、拼多多优势和劣势的 相关信息，接下来我将对这些信息进行整理和分析，形成一份详细的分析报告，并使用工具将输出 HTML 报告文件。\n行动：执行 HTML 报告工具\n观察：已获取到京东、淘宝、拼多多优势和劣势的相关信息，接下来我将对这些信息进行整理和分析，形成一份详细的分析报告。\n\n思考：我已经得到了答案，可以结束任务。\n行动：Finish\n\n现在请回答以下问题："
